// This file contains the list of all diagnostic categories for the Check
// toolchain
//
// The `define_categories` macro is preprocessed in the build script for the
// crate in order to generate the static registry. The body of the macro
// consists of a list of key-value pairs defining the categories that have an
// associated hyperlink, then a list of string literals defining the remaining
// categories without a link.

// PLEASE, DON'T EDIT THIS FILE BY HAND.
// Use `just new-lintrule` to create a new rule.
// lint rules are lexicographically sorted and
// must be between `define_categories! {\n` and `\n    ;\n`.

define_categories! {
    "lint/a11y/noAccessKey": "https://checkjs.dev/linter/rules/no-access-key",
    "lint/a11y/noAriaHiddenOnFocusable": "https://checkjs.dev/linter/rules/no-aria-hidden-on-focusable",
    "lint/a11y/noAriaUnsupportedElements": "https://checkjs.dev/linter/rules/no-aria-unsupported-elements",
    "lint/a11y/noAutofocus": "https://checkjs.dev/linter/rules/no-autofocus",
    "lint/a11y/noDistractingElements": "https://checkjs.dev/linter/rules/no-distracting-elements",
    "lint/a11y/noHeaderScope": "https://checkjs.dev/linter/rules/no-header-scope",
    "lint/a11y/noInteractiveElementToNoninteractiveRole": "https://checkjs.dev/linter/rules/no-interactive-element-to-noninteractive-role",
    "lint/a11y/noLabelWithoutControl": "https://checkjs.dev/linter/rules/no-label-without-control",
    "lint/a11y/noNoninteractiveElementInteractions": "https://checkjs.dev/linter/rules/no-noninteractive-element-interactions",
    "lint/a11y/noNoninteractiveElementToInteractiveRole": "https://checkjs.dev/linter/rules/no-noninteractive-element-to-interactive-role",
    "lint/a11y/noNoninteractiveTabindex": "https://checkjs.dev/linter/rules/no-noninteractive-tabindex",
    "lint/a11y/noPositiveTabindex": "https://checkjs.dev/linter/rules/no-positive-tabindex",
    "lint/a11y/noRedundantAlt": "https://checkjs.dev/linter/rules/no-redundant-alt",
    "lint/a11y/noRedundantRoles": "https://checkjs.dev/linter/rules/no-redundant-roles",
    "lint/a11y/noStaticElementInteractions": "https://checkjs.dev/linter/rules/no-static-element-interactions",
    "lint/a11y/noSvgWithoutTitle": "https://checkjs.dev/linter/rules/no-svg-without-title",
    "lint/a11y/useAltText": "https://checkjs.dev/linter/rules/use-alt-text",
    "lint/a11y/useAnchorContent": "https://checkjs.dev/linter/rules/use-anchor-content",
    "lint/a11y/useAriaActivedescendantWithTabindex": "https://checkjs.dev/linter/rules/use-aria-activedescendant-with-tabindex",
    "lint/a11y/useAriaPropsForRole": "https://checkjs.dev/linter/rules/use-aria-props-for-role",
    "lint/a11y/useAriaPropsSupportedByRole": "https://checkjs.dev/linter/rules/use-aria-props-supported-by-role",
    "lint/a11y/useButtonType": "https://checkjs.dev/linter/rules/use-button-type",
    "lint/a11y/useFocusableInteractive": "https://checkjs.dev/linter/rules/use-focusable-interactive",
    "lint/a11y/useGenericFontNames": "https://checkjs.dev/linter/rules/use-generic-font-names",
    "lint/a11y/useHeadingContent": "https://checkjs.dev/linter/rules/use-heading-content",
    "lint/a11y/useHtmlLang": "https://checkjs.dev/linter/rules/use-html-lang",
    "lint/a11y/useIframeTitle": "https://checkjs.dev/linter/rules/use-iframe-title",
    "lint/a11y/useKeyWithClickEvents": "https://checkjs.dev/linter/rules/use-key-with-click-events",
    "lint/a11y/useKeyWithMouseEvents": "https://checkjs.dev/linter/rules/use-key-with-mouse-events",
    "lint/a11y/useMediaCaption": "https://checkjs.dev/linter/rules/use-media-caption",
    "lint/a11y/useSemanticElements": "https://checkjs.dev/linter/rules/use-semantic-elements",
    "lint/a11y/useValidAnchor": "https://checkjs.dev/linter/rules/use-valid-anchor",
    "lint/a11y/useValidAriaProps": "https://checkjs.dev/linter/rules/use-valid-aria-props",
    "lint/a11y/useValidAriaRole": "https://checkjs.dev/linter/rules/use-valid-aria-role",
    "lint/a11y/useValidAriaValues": "https://checkjs.dev/linter/rules/use-valid-aria-values",
    "lint/a11y/useValidAutocomplete": "https://checkjs.dev/linter/rules/use-valid-autocomplete",
    "lint/a11y/useValidLang": "https://checkjs.dev/linter/rules/use-valid-lang",
    "lint/complexity/noAdjacentSpacesInRegex": "https://checkjs.dev/linter/rules/no-adjacent-spaces-in-regex",
    "lint/complexity/noArguments": "https://checkjs.dev/linter/rules/no-arguments",
    "lint/complexity/noBannedTypes": "https://checkjs.dev/linter/rules/no-banned-types",
    "lint/complexity/noCommaOperator": "https://checkjs.dev/linter/rules/no-comma-operator",
    "lint/complexity/noEmptyTypeParameters": "https://checkjs.dev/linter/rules/no-empty-type-parameters",
    "lint/complexity/noExcessiveCognitiveComplexity": "https://checkjs.dev/linter/rules/no-excessive-cognitive-complexity",
    "lint/complexity/noExcessiveLinesPerFunction": "https://checkjs.dev/linter/rules/no-excessive-lines-per-function",
    "lint/complexity/noExcessiveNestedTestSuites": "https://checkjs.dev/linter/rules/no-excessive-nested-test-suites",
    "lint/complexity/noExtraBooleanCast": "https://checkjs.dev/linter/rules/no-extra-boolean-cast",
    "lint/complexity/noFlatMapIdentity": "https://checkjs.dev/linter/rules/no-flat-map-identity",
    "lint/complexity/noForEach": "https://checkjs.dev/linter/rules/no-for-each",
    "lint/complexity/noImplicitCoercions": "https://checkjs.dev/linter/rules/no-implicit-coercions",
    "lint/complexity/noImportantStyles": "https://checkjs.dev/linter/rules/no-important-styles",
    "lint/complexity/noStaticOnlyClass": "https://checkjs.dev/linter/rules/no-static-only-class",
    "lint/complexity/noThisInStatic": "https://checkjs.dev/linter/rules/no-this-in-static",
    "lint/complexity/noUselessCatch": "https://checkjs.dev/linter/rules/no-useless-catch",
    "lint/complexity/noUselessConstructor": "https://checkjs.dev/linter/rules/no-useless-constructor",
    "lint/complexity/noUselessContinue": "https://checkjs.dev/linter/rules/no-useless-continue",
    "lint/complexity/noUselessEmptyExport": "https://checkjs.dev/linter/rules/no-useless-empty-export",
    "lint/complexity/noUselessEscapeInRegex": "https://checkjs.dev/linter/rules/no-useless-escape-in-regex",
    "lint/complexity/noUselessFragments": "https://checkjs.dev/linter/rules/no-useless-fragments",
    "lint/complexity/noUselessLabel": "https://checkjs.dev/linter/rules/no-useless-label",
    "lint/complexity/noUselessLoneBlockStatements": "https://checkjs.dev/linter/rules/no-useless-lone-block-statements",
    "lint/complexity/noUselessRename": "https://checkjs.dev/linter/rules/no-useless-rename",
    "lint/complexity/noUselessStringConcat": "https://checkjs.dev/linter/rules/no-useless-string-concat",
    "lint/complexity/noUselessStringRaw": "https://checkjs.dev/linter/rules/no-useless-string-raw",
    "lint/complexity/noUselessSwitchCase": "https://checkjs.dev/linter/rules/no-useless-switch-case",
    "lint/complexity/noUselessTernary": "https://checkjs.dev/linter/rules/no-useless-ternary",
    "lint/complexity/noUselessThisAlias": "https://checkjs.dev/linter/rules/no-useless-this-alias",
    "lint/complexity/noUselessTypeConstraint": "https://checkjs.dev/linter/rules/no-useless-type-constraint",
    "lint/complexity/noUselessUndefinedInitialization": "https://checkjs.dev/linter/rules/no-useless-undefined-initialization",
    "lint/complexity/noVoid": "https://checkjs.dev/linter/rules/no-void",
    "lint/complexity/useArrowFunction": "https://checkjs.dev/linter/rules/use-arrow-function",
    "lint/complexity/useDateNow": "https://checkjs.dev/linter/rules/use-date-now",
    "lint/complexity/useFlatMap": "https://checkjs.dev/linter/rules/use-flat-map",
    "lint/complexity/useIndexOf": "https://checkjs.dev/linter/rules/use-index-of",
    "lint/complexity/useLiteralKeys": "https://checkjs.dev/linter/rules/use-literal-keys",
    "lint/complexity/useNumericLiterals": "https://checkjs.dev/linter/rules/use-numeric-literals",
    "lint/complexity/useOptionalChain": "https://checkjs.dev/linter/rules/use-optional-chain",
    "lint/complexity/useRegexLiterals": "https://checkjs.dev/linter/rules/use-regex-literals",
    "lint/complexity/useSimpleNumberKeys": "https://checkjs.dev/linter/rules/use-simple-number-keys",
    "lint/complexity/useSimplifiedLogicExpression": "https://checkjs.dev/linter/rules/use-simplified-logic-expression",
    "lint/complexity/useWhile": "https://checkjs.dev/linter/rules/use-while",
    "lint/correctness/noChildrenProp": "https://checkjs.dev/linter/rules/no-children-prop",
    "lint/correctness/noConstAssign": "https://checkjs.dev/linter/rules/no-const-assign",
    "lint/correctness/noConstantCondition": "https://checkjs.dev/linter/rules/no-constant-condition",
    "lint/correctness/noConstantMathMinMaxClamp": "https://checkjs.dev/linter/rules/no-constant-math-min-max-clamp",
    "lint/correctness/noConstructorReturn": "https://checkjs.dev/linter/rules/no-constructor-return",
    "lint/correctness/noEmptyCharacterClassInRegex": "https://checkjs.dev/linter/rules/no-empty-character-class-in-regex",
    "lint/correctness/noEmptyPattern": "https://checkjs.dev/linter/rules/no-empty-pattern",
    "lint/correctness/noGlobalDirnameFilename": "https://checkjs.dev/linter/rules/no-global-dirname-filename",
    "lint/correctness/noGlobalObjectCalls": "https://checkjs.dev/linter/rules/no-global-object-calls",
    "lint/correctness/noInnerDeclarations": "https://checkjs.dev/linter/rules/no-inner-declarations",
    "lint/correctness/noInvalidBuiltinInstantiation": "https://checkjs.dev/linter/rules/no-invalid-builtin-instantiation",
    "lint/correctness/noInvalidConstructorSuper": "https://checkjs.dev/linter/rules/no-invalid-constructor-super",
    "lint/correctness/noInvalidDirectionInLinearGradient": "https://checkjs.dev/linter/rules/no-invalid-direction-in-linear-gradient",
    "lint/correctness/noInvalidGridAreas": "https://checkjs.dev/linter/rules/use-consistent-grid-areas",
    "lint/correctness/noInvalidNewBuiltin": "https://checkjs.dev/linter/rules/no-invalid-new-builtin",
    "lint/correctness/noInvalidPositionAtImportRule": "https://checkjs.dev/linter/rules/no-invalid-position-at-import-rule",
    "lint/correctness/noInvalidUseBeforeDeclaration": "https://checkjs.dev/linter/rules/no-invalid-use-before-declaration",
    "lint/correctness/noMissingVarFunction": "https://checkjs.dev/linter/rules/no-missing-var-function",
    "lint/correctness/noNestedComponentDefinitions": "https://checkjs.dev/linter/rules/no-nested-component-definitions",
    "lint/correctness/noNewSymbol": "https://checkjs.dev/linter/rules/no-new-symbol",
    "lint/correctness/noNodejsModules": "https://checkjs.dev/linter/rules/no-nodejs-modules",
    "lint/correctness/noNonoctalDecimalEscape": "https://checkjs.dev/linter/rules/no-nonoctal-decimal-escape",
    "lint/correctness/noPrecisionLoss": "https://checkjs.dev/linter/rules/no-precision-loss",
    "lint/correctness/noPrivateImports": "https://checkjs.dev/linter/rules/no-private-imports",
    "lint/correctness/noProcessGlobal": "https://checkjs.dev/linter/rules/no-process-global",
    "lint/correctness/noReactPropAssignments": "https://checkjs.dev/linter/rules/no-react-prop-assignments",
    "lint/correctness/noRenderReturnValue": "https://checkjs.dev/linter/rules/no-render-return-value",
    "lint/correctness/noRestrictedElements": "https://checkjs.dev/linter/rules/no-restricted-elements",
    "lint/correctness/noSelfAssign": "https://checkjs.dev/linter/rules/no-self-assign",
    "lint/correctness/noSetterReturn": "https://checkjs.dev/linter/rules/no-setter-return",
    "lint/correctness/noSolidDestructuredProps": "https://checkjs.dev/linter/rules/no-solid-destructured-props",
    "lint/correctness/noStringCaseMismatch": "https://checkjs.dev/linter/rules/no-string-case-mismatch",
    "lint/correctness/noSwitchDeclarations": "https://checkjs.dev/linter/rules/no-switch-declarations",
    "lint/correctness/noUndeclaredDependencies": "https://checkjs.dev/linter/rules/no-undeclared-dependencies",
    "lint/correctness/noUndeclaredVariables": "https://checkjs.dev/linter/rules/no-undeclared-variables",
    "lint/correctness/noUnknownFunction": "https://checkjs.dev/linter/rules/no-unknown-function",
    "lint/correctness/noUnknownMediaFeatureName": "https://checkjs.dev/linter/rules/no-unknown-media-feature-name",
    "lint/correctness/noUnknownProperty": "https://checkjs.dev/linter/rules/no-unknown-property",
    "lint/correctness/noUnknownPseudoClass": "https://checkjs.dev/linter/rules/no-unknown-pseudo-class",
    "lint/correctness/noUnknownPseudoClassSelector": "https://checkjs.dev/linter/rules/no-unknown-pseudo-class-selector",
    "lint/correctness/noUnknownPseudoElement": "https://checkjs.dev/linter/rules/no-unknown-selector-pseudo-element",
    "lint/correctness/noUnknownTypeSelector": "https://checkjs.dev/linter/rules/no-unknown-type-selector",
    "lint/correctness/noUnknownUnit": "https://checkjs.dev/linter/rules/no-unknown-unit",
    "lint/correctness/noUnmatchableAnbSelector": "https://checkjs.dev/linter/rules/no-unmatchable-anb-selector",
    "lint/correctness/noUnreachable": "https://checkjs.dev/linter/rules/no-unreachable",
    "lint/correctness/noUnreachableSuper": "https://checkjs.dev/docs/linter/rules/no-unreachable-super",
    "lint/correctness/noUnsafeFinally": "https://checkjs.dev/linter/rules/no-unsafe-finally",
    "lint/correctness/noUnsafeOptionalChaining": "https://checkjs.dev/linter/rules/no-unsafe-optional-chaining",
    "lint/correctness/noUnusedFunctionParameters": "https://checkjs.dev/linter/rules/no-unused-function-parameters",
    "lint/correctness/noUnusedImports": "https://checkjs.dev/linter/rules/no-unused-imports",
    "lint/correctness/noUnusedLabels": "https://checkjs.dev/linter/rules/no-unused-labels",
    "lint/correctness/noUnusedPrivateClassMembers": "https://checkjs.dev/linter/rules/no-unused-private-class-members",
    "lint/correctness/noUnusedVariables": "https://checkjs.dev/linter/rules/no-unused-variables",
    "lint/correctness/noVoidElementsWithChildren": "https://checkjs.dev/linter/rules/no-void-elements-with-children",
    "lint/correctness/noVoidTypeReturn": "https://checkjs.dev/linter/rules/no-void-type-return",
    "lint/correctness/useExhaustiveDependencies": "https://checkjs.dev/linter/rules/use-exhaustive-dependencies",
    "lint/correctness/useGraphqlNamedOperations": "https://checkjs.dev/linter/rules/use-graphql-named-operations",
    "lint/correctness/useHookAtTopLevel": "https://checkjs.dev/linter/rules/use-hook-at-top-level",
    "lint/correctness/useImportExtensions": "https://checkjs.dev/linter/rules/use-import-extensions",
    "lint/correctness/useIsNan": "https://checkjs.dev/linter/rules/use-is-nan",
    "lint/correctness/useJsonImportAttributes": "https://checkjs.dev/linter/rules/use-json-import-attributes",
    "lint/correctness/useJsxKeyInIterable": "https://checkjs.dev/linter/rules/use-jsx-key-in-iterable",
    "lint/correctness/useParseIntRadix": "https://checkjs.dev/linter/rules/use-parse-int-radix",
    "lint/correctness/useSingleJsDocAsterisk": "https://checkjs.dev/linter/rules/use-single-js-doc-asterisk",
    "lint/correctness/useUniqueElementIds": "https://checkjs.dev/linter/rules/use-unique-element-ids",
    "lint/correctness/useValidForDirection": "https://checkjs.dev/linter/rules/use-valid-for-direction",
    "lint/correctness/useValidTypeof": "https://checkjs.dev/linter/rules/use-valid-typeof",
    "lint/correctness/useYield": "https://checkjs.dev/linter/rules/use-yield",
    "lint/nursery/noColorInvalidHex": "https://checkjs.dev/linter/rules/no-color-invalid-hex",
    "lint/nursery/noFloatingPromises": "https://checkjs.dev/linter/rules/no-floating-promises",
    "lint/nursery/noImplicitCoercion": "https://checkjs.dev/linter/rules/no-implicit-coercion",
    "lint/nursery/noImportCycles": "https://checkjs.dev/linter/rules/no-import-cycles",
    "lint/nursery/noJsxLiterals": "https://checkjs.dev/linter/rules/no-jsx-literals",
    "lint/nursery/noMissingGenericFamilyKeyword": "https://checkjs.dev/linter/rules/no-missing-generic-family-keyword",
    "lint/nursery/noMisusedPromises": "https://checkjs.dev/linter/rules/no-misused-promises",
    "lint/nursery/noNextAsyncClientComponent": "https://checkjs.dev/linter/rules/no-next-async-client-component",
    "lint/nursery/noNonNullAssertedOptionalChain": "https://checkjs.dev/linter/rules/no-non-null-asserted-optional-chain",
    "lint/nursery/noQwikUseVisibleTask": "https://checkjs.dev/linter/rules/no-qwik-use-visible-task",
    "lint/nursery/noSecrets": "https://checkjs.dev/linter/rules/no-secrets",
    "lint/nursery/noShadow": "https://checkjs.dev/linter/rules/no-shadow",
    "lint/nursery/noUnnecessaryConditions": "https://checkjs.dev/linter/rules/no-unnecessary-conditions",
    "lint/nursery/noUnresolvedImports": "https://checkjs.dev/linter/rules/no-unresolved-imports",
    "lint/nursery/noUnwantedPolyfillio": "https://checkjs.dev/linter/rules/no-unwanted-polyfillio",
    "lint/nursery/noUselessBackrefInRegex": "https://checkjs.dev/linter/rules/no-useless-backref-in-regex",
    "lint/nursery/noUselessCatchBinding": "https://checkjs.dev/linter/rules/no-useless-catch-binding",
    "lint/nursery/noUselessUndefined": "https://checkjs.dev/linter/rules/no-useless-undefined",
    "lint/nursery/noVueDataObjectDeclaration": "https://checkjs.dev/linter/rules/no-vue-data-object-declaration",
    "lint/nursery/noVueReservedKeys": "https://checkjs.dev/linter/rules/no-vue-reserved-keys",
    "lint/nursery/noVueReservedProps": "https://checkjs.dev/linter/rules/no-vue-reserved-props",
    "lint/nursery/useAnchorHref": "https://checkjs.dev/linter/rules/use-anchor-href",
    "lint/nursery/useCheckSuppressionComment": "https://checkjs.dev/linter/rules/use-check-suppression-comment",
    "lint/nursery/useConsistentArrowReturn": "https://checkjs.dev/linter/rules/use-consistent-arrow-return",
    "lint/nursery/useConsistentObjectDefinition": "https://checkjs.dev/linter/rules/use-consistent-object-definition",
    "lint/nursery/useConsistentTypeDefinitions": "https://checkjs.dev/linter/rules/use-consistent-type-definitions",
    "lint/nursery/useExhaustiveSwitchCases": "https://checkjs.dev/linter/rules/use-exhaustive-switch-cases",
    "lint/nursery/useExplicitFunctionReturnType": "https://checkjs.dev/linter/rules/use-explicit-type",
    "lint/nursery/useExplicitType": "https://checkjs.dev/linter/rules/use-explicit-type",
    "lint/nursery/useImageSize": "https://checkjs.dev/linter/rules/use-image-size",
    "lint/nursery/useImportRestrictions": "https://checkjs.dev/linter/rules/use-import-restrictions",
    "lint/nursery/useJsxCurlyBraceConvention": "https://checkjs.dev/linter/rules/use-jsx-curly-brace-convention",
    "lint/nursery/useMaxParams": "https://checkjs.dev/linter/rules/use-max-params",
    "lint/nursery/useQwikClasslist": "https://checkjs.dev/linter/rules/use-qwik-classlist",
    "lint/nursery/useReactFunctionComponents": "https://checkjs.dev/linter/rules/use-react-function-components",
    "lint/nursery/useSortedClasses": "https://checkjs.dev/linter/rules/use-sorted-classes",
    "lint/nursery/useVueMultiWordComponentNames": "https://checkjs.dev/linter/rules/use-vue-multi-word-component-names",
    "lint/performance/noAccumulatingSpread": "https://checkjs.dev/linter/rules/no-accumulating-spread",
    "lint/performance/noAwaitInLoops": "https://checkjs.dev/linter/rules/no-await-in-loops",
    "lint/performance/noBarrelFile": "https://checkjs.dev/linter/rules/no-barrel-file",
    "lint/performance/noDelete": "https://checkjs.dev/linter/rules/no-delete",
    "lint/performance/noDynamicNamespaceImportAccess": "https://checkjs.dev/linter/rules/no-dynamic-namespace-import-access",
    "lint/performance/noImgElement": "https://checkjs.dev/linter/rules/no-img-element",
    "lint/performance/noNamespaceImport": "https://checkjs.dev/linter/rules/no-namespace-import",
    "lint/performance/noReExportAll": "https://checkjs.dev/linter/rules/no-re-export-all",
    "lint/performance/noUnwantedPolyfillio": "https://checkjs.dev/linter/rules/no-unwanted-polyfillio",
    "lint/performance/useGoogleFontPreconnect": "https://checkjs.dev/linter/rules/use-google-font-preconnect",
    "lint/performance/useSolidForComponent": "https://checkjs.dev/linter/rules/use-solid-for-component",
    "lint/performance/useTopLevelRegex": "https://checkjs.dev/linter/rules/use-top-level-regex",
    "lint/security/noBlankTarget": "https://checkjs.dev/linter/rules/no-blank-target",
    "lint/security/noDangerouslySetInnerHtml": "https://checkjs.dev/linter/rules/no-dangerously-set-inner-html",
    "lint/security/noDangerouslySetInnerHtmlWithChildren": "https://checkjs.dev/linter/rules/no-dangerously-set-inner-html-with-children",
    "lint/security/noGlobalEval": "https://checkjs.dev/linter/rules/no-global-eval",
    "lint/style/noCommonJs": "https://checkjs.dev/linter/rules/no-common-js",
    "lint/style/noDefaultExport": "https://checkjs.dev/linter/rules/no-default-export",
    "lint/style/noDescendingSpecificity": "https://checkjs.dev/linter/rules/no-descending-specificity",
    "lint/style/noDoneCallback": "https://checkjs.dev/linter/rules/no-done-callback",
    "lint/style/noEnum": "https://checkjs.dev/linter/rules/no-enum",
    "lint/style/noExportedImports": "https://checkjs.dev/linter/rules/no-exported-imports",
    "lint/style/noHeadElement": "https://checkjs.dev/linter/rules/no-head-element",
    "lint/style/noImplicitBoolean": "https://checkjs.dev/linter/rules/no-implicit-boolean",
    "lint/style/noInferrableTypes": "https://checkjs.dev/linter/rules/no-inferrable-types",
    "lint/style/noMagicNumbers": "https://checkjs.dev/linter/rules/no-magic-numbers",
    "lint/style/noNamespace": "https://checkjs.dev/linter/rules/no-namespace",
    "lint/style/noNegationElse": "https://checkjs.dev/linter/rules/no-negation-else",
    "lint/style/noNestedTernary": "https://checkjs.dev/linter/rules/no-nested-ternary",
    "lint/style/noNonNullAssertion": "https://checkjs.dev/linter/rules/no-non-null-assertion",
    "lint/style/noParameterAssign": "https://checkjs.dev/linter/rules/no-parameter-assign",
    "lint/style/noParameterProperties": "https://checkjs.dev/linter/rules/no-parameter-properties",
    "lint/style/noProcessEnv": "https://checkjs.dev/linter/rules/no-process-env",
    "lint/style/noRestrictedGlobals": "https://checkjs.dev/linter/rules/no-restricted-globals",
    "lint/style/noRestrictedImports": "https://checkjs.dev/linter/rules/no-restricted-imports",
    "lint/style/noRestrictedTypes": "https://checkjs.dev/linter/rules/no-restricted-types",
    "lint/style/noShoutyConstants": "https://checkjs.dev/linter/rules/no-shouty-constants",
    "lint/style/noSubstr": "https://checkjs.dev/linter/rules/no-substr",
    "lint/style/noUnusedTemplateLiteral": "https://checkjs.dev/linter/rules/no-unused-template-literal",
    "lint/style/noUselessElse": "https://checkjs.dev/linter/rules/no-useless-else",
    "lint/style/noValueAtRule": "https://checkjs.dev/linter/rules/no-value-at-rule",
    "lint/style/noYodaExpression": "https://checkjs.dev/linter/rules/no-yoda-expression",
    "lint/style/useArrayLiterals": "https://checkjs.dev/linter/rules/use-array-literals",
    "lint/style/useAsConstAssertion": "https://checkjs.dev/linter/rules/use-as-const-assertion",
    "lint/style/useAtIndex": "https://checkjs.dev/linter/rules/use-at-index",
    "lint/style/useBlockStatements": "https://checkjs.dev/linter/rules/use-block-statements",
    "lint/style/useCollapsedElseIf": "https://checkjs.dev/linter/rules/use-collapsed-else-if",
    "lint/style/useCollapsedIf": "https://checkjs.dev/linter/rules/use-collapsed-if",
    "lint/style/useComponentExportOnlyModules": "https://checkjs.dev/linter/rules/use-component-export-only-modules",
    "lint/style/useConsistentArrayType": "https://checkjs.dev/linter/rules/use-consistent-array-type",
    "lint/style/useConsistentBuiltinInstantiation": "https://checkjs.dev/linter/rules/use-consistent-new-builtin",
    "lint/style/useConsistentCurlyBraces": "https://checkjs.dev/linter/rules/use-consistent-curly-braces",
    "lint/style/useConsistentMemberAccessibility": "https://checkjs.dev/linter/rules/use-consistent-member-accessibility",
    "lint/style/useConsistentObjectDefinitions": "https://checkjs.dev/linter/rules/use-consistent-object-definitions",
    "lint/style/useConst": "https://checkjs.dev/linter/rules/use-const",
    "lint/style/useDefaultParameterLast": "https://checkjs.dev/linter/rules/use-default-parameter-last",
    "lint/style/useDefaultSwitchClause": "https://checkjs.dev/linter/rules/use-default-switch-clause",
    "lint/style/useDeprecatedReason": "https://checkjs.dev/linter/rules/use-deprecated-reason",
    "lint/style/useEnumInitializers": "https://checkjs.dev/linter/rules/use-enum-initializers",
    "lint/style/useExplicitLengthCheck": "https://checkjs.dev/linter/rules/use-explicit-length-check",
    "lint/style/useExponentiationOperator": "https://checkjs.dev/linter/rules/use-exponentiation-operator",
    "lint/style/useExportType": "https://checkjs.dev/linter/rules/use-export-type",
    "lint/style/useExportsLast": "https://checkjs.dev/linter/rules/use-exports-last",
    "lint/style/useFilenamingConvention": "https://checkjs.dev/linter/rules/use-filenaming-convention",
    "lint/style/useForOf": "https://checkjs.dev/linter/rules/use-for-of",
    "lint/style/useFragmentSyntax": "https://checkjs.dev/linter/rules/use-fragment-syntax",
    "lint/style/useGraphqlNamingConvention": "https://checkjs.dev/linter/rules/use-graphql-naming-convention",
    "lint/style/useGroupedAccessorPairs": "https://checkjs.dev/linter/rules/use-grouped-accessor-pairs",
    "lint/style/useImportType": "https://checkjs.dev/linter/rules/use-import-type",
    "lint/style/useLiteralEnumMembers": "https://checkjs.dev/linter/rules/use-literal-enum-members",
    "lint/style/useNamingConvention": "https://checkjs.dev/linter/rules/use-naming-convention",
    "lint/style/useNodeAssertStrict": "https://checkjs.dev/linter/rules/use-node-assert-strict",
    "lint/style/useNodejsImportProtocol": "https://checkjs.dev/linter/rules/use-nodejs-import-protocol",
    "lint/style/useNumberNamespace": "https://checkjs.dev/linter/rules/use-number-namespace",
    "lint/style/useNumericSeparators": "https://checkjs.dev/linter/rules/use-numeric-separators",
    "lint/style/useObjectSpread": "https://checkjs.dev/linter/rules/use-object-spread",
    "lint/style/useReadonlyClassProperties": "https://checkjs.dev/linter/rules/use-readonly-class-properties",
    "lint/style/useSelfClosingElements": "https://checkjs.dev/linter/rules/use-self-closing-elements",
    "lint/style/useShorthandArrayType": "https://checkjs.dev/linter/rules/use-shorthand-array-type",
    "lint/style/useShorthandAssign": "https://checkjs.dev/linter/rules/use-shorthand-assign",
    "lint/style/useShorthandFunctionType": "https://checkjs.dev/linter/rules/use-shorthand-function-type",
    "lint/style/useSingleCaseStatement": "https://checkjs.dev/linter/rules/use-single-case-statement",
    "lint/style/useSingleVarDeclarator": "https://checkjs.dev/linter/rules/use-single-var-declarator",
    "lint/style/useSymbolDescription": "https://checkjs.dev/linter/rules/use-symbol-description",
    "lint/style/useTemplate": "https://checkjs.dev/linter/rules/use-template",
    "lint/style/useThrowNewError": "https://checkjs.dev/linter/rules/use-throw-new-error",
    "lint/style/useThrowOnlyError": "https://checkjs.dev/linter/rules/use-throw-only-error",
    "lint/style/useTrimStartEnd": "https://checkjs.dev/linter/rules/use-trim-start-end",
    "lint/style/useUnifiedTypeSignatures": "https://checkjs.dev/linter/rules/use-unified-type-signatures",
    "lint/suspicious/noAlert": "https://checkjs.dev/linter/rules/no-alert",
    "lint/suspicious/noApproximativeNumericConstant": "https://checkjs.dev/linter/rules/no-approximative-numeric-constant",
    "lint/suspicious/noArrayIndexKey": "https://checkjs.dev/linter/rules/no-array-index-key",
    "lint/suspicious/noAssignInExpressions": "https://checkjs.dev/linter/rules/no-assign-in-expressions",
    "lint/suspicious/noAsyncPromiseExecutor": "https://checkjs.dev/linter/rules/no-async-promise-executor",
    "lint/suspicious/noCheckFirstException": "https://checkjs.dev/linter/rules/no-check-first-exception",
    "lint/suspicious/noBitwiseOperators": "https://checkjs.dev/linter/rules/no-bitwise-operators",
    "lint/suspicious/noCatchAssign": "https://checkjs.dev/linter/rules/no-catch-assign",
    "lint/suspicious/noClassAssign": "https://checkjs.dev/linter/rules/no-class-assign",
    "lint/suspicious/noCommentText": "https://checkjs.dev/linter/rules/no-comment-text",
    "lint/suspicious/noCompareNegZero": "https://checkjs.dev/linter/rules/no-compare-neg-zero",
    "lint/suspicious/noConfusingLabels": "https://checkjs.dev/linter/rules/no-confusing-labels",
    "lint/suspicious/noConfusingVoidType": "https://checkjs.dev/linter/rules/no-confusing-void-type",
    "lint/suspicious/noConsole": "https://checkjs.dev/linter/rules/no-console",
    "lint/suspicious/noConstEnum": "https://checkjs.dev/linter/rules/no-const-enum",
    "lint/suspicious/noConstantBinaryExpressions": "https://checkjs.dev/linter/rules/no-constant-binary-expressions",
    "lint/suspicious/noControlCharactersInRegex": "https://checkjs.dev/linter/rules/no-control-characters-in-regex",
    "lint/suspicious/noDebugger": "https://checkjs.dev/linter/rules/no-debugger",
    "lint/suspicious/noDocumentCookie": "https://checkjs.dev/linter/rules/no-document-cookie",
    "lint/suspicious/noDocumentImportInPage": "https://checkjs.dev/linter/rules/no-document-import-in-page",
    "lint/suspicious/noDoubleEquals": "https://checkjs.dev/linter/rules/no-double-equals",
    "lint/suspicious/noDuplicateAtImportRules": "https://checkjs.dev/linter/rules/no-duplicate-at-import-rules",
    "lint/suspicious/noDuplicateCase": "https://checkjs.dev/linter/rules/no-duplicate-case",
    "lint/suspicious/noDuplicateClassMembers": "https://checkjs.dev/linter/rules/no-duplicate-class-members",
    "lint/suspicious/noDuplicateCustomProperties": "https://checkjs.dev/linter/rules/no-duplicate-custom-properties",
    "lint/nursery/noDuplicateDependencies": "https://checkjs.dev/linter/rules/no-duplicate-dependencies",
    "lint/suspicious/noDuplicateElseIf": "https://checkjs.dev/linter/rules/no-duplicate-else-if",
    "lint/suspicious/noDuplicateFields": "https://checkjs.dev/linter/rules/no-duplicate-fields",
    "lint/suspicious/noDuplicateFontNames": "https://checkjs.dev/linter/rules/no-font-family-duplicate-names",
    "lint/suspicious/noDuplicateJsxProps": "https://checkjs.dev/linter/rules/no-duplicate-jsx-props",
    "lint/suspicious/noDuplicateObjectKeys": "https://checkjs.dev/linter/rules/no-duplicate-object-keys",
    "lint/suspicious/noDuplicateParameters": "https://checkjs.dev/linter/rules/no-duplicate-parameters",
    "lint/suspicious/noDuplicateProperties": "https://checkjs.dev/linter/rules/no-duplicate-properties",
    "lint/suspicious/noDuplicateSelectorsKeyframeBlock": "https://checkjs.dev/linter/rules/no-duplicate-selectors-keyframe-block",
    "lint/suspicious/noDuplicateTestHooks": "https://checkjs.dev/linter/rules/no-duplicate-test-hooks",
    "lint/suspicious/noEmptyBlock": "https://checkjs.dev/linter/rules/no-empty-block",
    "lint/suspicious/noEmptyBlockStatements": "https://checkjs.dev/linter/rules/no-empty-block-statements",
    "lint/suspicious/noEmptyInterface": "https://checkjs.dev/linter/rules/no-empty-interface",
    "lint/suspicious/noEvolvingTypes": "https://checkjs.dev/linter/rules/no-evolving-types",
    "lint/suspicious/noExplicitAny": "https://checkjs.dev/linter/rules/no-explicit-any",
    "lint/suspicious/noExportsInTest": "https://checkjs.dev/linter/rules/no-exports-in-test",
    "lint/suspicious/noExtraNonNullAssertion": "https://checkjs.dev/linter/rules/no-extra-non-null-assertion",
    "lint/suspicious/noFallthroughSwitchClause": "https://checkjs.dev/linter/rules/no-fallthrough-switch-clause",
    "lint/suspicious/noFocusedTests": "https://checkjs.dev/linter/rules/no-focused-tests",
    "lint/suspicious/noFunctionAssign": "https://checkjs.dev/linter/rules/no-function-assign",
    "lint/suspicious/noGlobalAssign": "https://checkjs.dev/linter/rules/no-global-assign",
    "lint/suspicious/noGlobalIsFinite": "https://checkjs.dev/linter/rules/no-global-is-finite",
    "lint/suspicious/noGlobalIsNan": "https://checkjs.dev/linter/rules/no-global-is-nan",
    "lint/suspicious/noHeadImportInDocument": "https://checkjs.dev/linter/rules/no-head-import-in-document",
    "lint/suspicious/noImplicitAnyLet": "https://checkjs.dev/linter/rules/no-implicit-any-let",
    "lint/suspicious/noImportAssign": "https://checkjs.dev/linter/rules/no-import-assign",
    "lint/suspicious/noImportantInKeyframe": "https://checkjs.dev/linter/rules/no-important-in-keyframe",
    "lint/suspicious/noIrregularWhitespace": "https://checkjs.dev/linter/rules/no-irregular-whitespace",
    "lint/suspicious/noLabelVar": "https://checkjs.dev/linter/rules/no-label-var",
    "lint/suspicious/noMisleadingCharacterClass": "https://checkjs.dev/linter/rules/no-misleading-character-class",
    "lint/suspicious/noMisleadingInstantiator": "https://checkjs.dev/linter/rules/no-misleading-instantiator",
    "lint/suspicious/noMisplacedAssertion": "https://checkjs.dev/linter/rules/no-misplaced-assertion",
    "lint/suspicious/noMisrefactoredShorthandAssign": "https://checkjs.dev/linter/rules/no-misrefactored-shorthand-assign",
    "lint/suspicious/noOctalEscape": "https://checkjs.dev/linter/rules/no-octal-escape",
    "lint/suspicious/noPrototypeBuiltins": "https://checkjs.dev/linter/rules/no-prototype-builtins",
    "lint/suspicious/noQuickfixCheck": "https://checkjs.dev/linter/rules/no-quickfix-check",
    "lint/suspicious/noReactSpecificProps": "https://checkjs.dev/linter/rules/no-react-specific-props",
    "lint/suspicious/noRedeclare": "https://checkjs.dev/linter/rules/no-redeclare",
    "lint/suspicious/noRedundantUseStrict": "https://checkjs.dev/linter/rules/no-redundant-use-strict",
    "lint/suspicious/noSelfCompare": "https://checkjs.dev/linter/rules/no-self-compare",
    "lint/suspicious/noShadowRestrictedNames": "https://checkjs.dev/linter/rules/no-shadow-restricted-names",
    "lint/suspicious/noShorthandPropertyOverrides": "https://checkjs.dev/linter/rules/no-shorthand-property-overrides",
    "lint/suspicious/noSkippedTests": "https://checkjs.dev/linter/rules/no-skipped-tests",
    "lint/suspicious/noSparseArray": "https://checkjs.dev/linter/rules/no-sparse-array",
    "lint/suspicious/noSuspiciousSemicolonInJsx": "https://checkjs.dev/linter/rules/no-suspicious-semicolon-in-jsx",
    "lint/suspicious/noTemplateCurlyInString": "https://checkjs.dev/linter/rules/no-template-curly-in-string",
    "lint/suspicious/noThenProperty": "https://checkjs.dev/linter/rules/no-then-property",
    "lint/suspicious/noTsIgnore": "https://checkjs.dev/linter/rules/no-ts-ignore",
    "lint/suspicious/noUnassignedVariables": "https://checkjs.dev/linter/rules/no-unassigned-variables",
    "lint/suspicious/noUnknownAtRules": "https://checkjs.dev/linter/rules/no-unknown-at-rules",
    "lint/suspicious/noUnsafeDeclarationMerging": "https://checkjs.dev/linter/rules/no-unsafe-declaration-merging",
    "lint/suspicious/noUnsafeNegation": "https://checkjs.dev/linter/rules/no-unsafe-negation",
    "lint/suspicious/noUselessEscapeInString": "https://checkjs.dev/linter/rules/no-useless-escape-in-string",
    "lint/suspicious/noUselessRegexBackrefs": "https://checkjs.dev/linter/rules/no-useless-regex-backrefs",
    "lint/suspicious/noVar": "https://checkjs.dev/linter/rules/no-var",
    "lint/suspicious/noWith": "https://checkjs.dev/linter/rules/no-with",
    "lint/suspicious/useAdjacentOverloadSignatures": "https://checkjs.dev/linter/rules/use-adjacent-overload-signatures",
    "lint/suspicious/useAwait": "https://checkjs.dev/linter/rules/use-await",
    "lint/suspicious/useCheckIgnoreFolder": "https://checkjs.dev/linter/rules/use-check-ignore-folder",
    "lint/suspicious/useDefaultSwitchClauseLast": "https://checkjs.dev/linter/rules/use-default-switch-clause-last",
    "lint/suspicious/useErrorMessage": "https://checkjs.dev/linter/rules/use-error-message",
    "lint/suspicious/useGetterReturn": "https://checkjs.dev/linter/rules/use-getter-return",
    "lint/suspicious/useGoogleFontDisplay": "https://checkjs.dev/linter/rules/use-google-font-display",
    "lint/suspicious/useGuardForIn": "https://checkjs.dev/linter/rules/use-guard-for-in",
    "lint/suspicious/useIsArray": "https://checkjs.dev/linter/rules/use-is-array",
    "lint/suspicious/useIterableCallbackReturn": "https://checkjs.dev/linter/rules/use-iterable-callback-return",
    "lint/suspicious/useNamespaceKeyword": "https://checkjs.dev/linter/rules/use-namespace-keyword",
    "lint/suspicious/useNumberToFixedDigitsArgument": "https://checkjs.dev/linter/rules/use-number-to-fixed-digits-argument",
    "lint/suspicious/useStaticResponseMethods": "https://checkjs.dev/linter/rules/use-static-response-methods",
    "lint/suspicious/useStrictMode": "https://checkjs.dev/linter/rules/use-strict-mode",
    // end lint rules
    // start assist actions
    "assist/source/useSortedKeys": "https://checkjs.dev/assist/actions/use-sorted-keys",
    "assist/source/useSortedProperties": "https://checkjs.dev/assist/actions/use-sorted-properties",
    "assist/source/useSortedAttributes": "https://checkjs.dev/assist/actions/use-sorted-attributes",
    "assist/source/organizeImports": "https://checkjs.dev/assist/actions/organize-imports",
    // end assist actions
    ; // start syntax rules
    "syntax/correctness/noTypeOnlyImportAttributes",
    "syntax/correctness/noSuperWithoutExtends",
    "syntax/correctness/noInitializerWithDefinite",
    "syntax/correctness/noDuplicatePrivateClassMembers",
    // end syntax rules

    // General categories
    "files/missingHandler",
    "format",
    "check",
    "ci",
    "stdin",
    "configuration",
    "assist",
    "migrate",
    "deserialize",
    "plugin",
    "project",
    "search",
    "internalError/io",
    "internalError/fs",
    "internalError/panic",
    "reporter/parse",
    "reporter/format",
    "reporter/violations",
    // parse categories
    "parse",

    // Lint groups
    "lint",
    "lint/a11y",
    "lint/complexity",
    "lint/correctness",
    "lint/nursery",
    "lint/performance",
    "lint/security",
    "lint/style",
    "lint/suspicious",
    "lint/plugin",

    // Suppression comments
    "suppressions/parse",
    "suppressions/unknownGroup",
    "suppressions/unknownRule",
    "suppressions/unknownAction",
    "suppressions/unused",
    "suppressions/incorrect",
    // Used in tests and examples
    "args/fileNotFound",
    "flags/invalid",
    "semanticTests",
}
