[package]
authors.workspace    = true
categories.workspace = true
description          = "JSDoc comment handling helpers"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_jsdoc_comment"
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
check_formatter    = { workspace = true }
check_js_syntax    = { workspace = true }
check_js_type_info = { workspace = true }
check_rowan        = { workspace = true }
