[package]
authors.workspace    = true
description          = "Utilities to create JavaScript AST for check_js_parser"
documentation        = "https://docs.rs/check_js_factory"
edition.workspace    = true
license.workspace    = true
name                 = "check_js_factory"
repository.workspace = true
version              = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check_js_syntax = { workspace = true }
check_rowan     = { workspace = true }

[lints]
workspace = true
