[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to convert string cases"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_string_case"
repository.workspace = true
version              = "0.5.7"

[dependencies]
check_rowan = { workspace = true, optional = true }

[features]
check_rowan = ["dep:check_rowan"]

[lints]
workspace = true
