[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities for tests"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_test_utils"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_rgb             = "0.2.0"
check_analyze        = { workspace = true }
check_configuration  = { workspace = true }
check_console        = { workspace = true }
check_deserialize    = { workspace = true }
check_diagnostics    = { workspace = true }
check_formatter      = { workspace = true }
check_fs             = { workspace = true }
check_js_analyze     = { workspace = true }
check_js_parser      = { workspace = true }
check_js_type_info   = { workspace = true }
check_json_parser    = { workspace = true }
check_module_graph   = { workspace = true }
check_package        = { workspace = true }
check_project_layout = { workspace = true }
check_rowan          = { workspace = true, features = ["countme"] }
check_service        = { workspace = true }
check_string_case    = { workspace = true }
camino               = { workspace = true }
countme              = { workspace = true, features = ["enable"] }
json_comments        = "0.2.2"
serde_json           = { workspace = true }
similar              = { workspace = true }
ureq                 = { workspace = true }
url                  = { workspace = true }


[lints]
workspace = true
