# Automatically add language labels to documentation issues that provide a link
# to the documentation page by extracting the language from the given URL. When
# adding a new language, make sure to add the corresponding language code to the
# negative lookahead in the english regex, so that it doesn't match the english
# documentation URL.

'Lang-Chinese':
  - 'https://checkjs.dev/zh-cn/'
'Lang-English':
  - 'https://checkjs.dev/(?!(zh-cn|fr|ja|pt-br|es|uk))'
'Lang-French':
  - 'https://checkjs.dev/fr/'
'Lang-Japanese':
  - 'https://checkjs.dev/ja/'
'Lang-Portuguese':
  - 'https://checkjs.dev/pt-br/'
'Lang-Spanish':
  - 'https://checkjs.dev/es/'
'Lang-Ukrainian':
  - 'https://checkjs.dev/uk/'
