# See https://github.com/actions/labeler

A-Cli:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_cli/**
    - crates/check_fs/**
    - crates/check_console/**

A-Core:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_deserializer/**
    - crates/check_fs/**
    - crates/check_rowan/**
    - crates/check_text_edit/**
    - crates/check_text_size/**
    - crates/check_suppression/**
    - crates/check_markup/**

A-Project:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_service/**
    - crates/check_configuration/**
    - crates/check_module_graph/**
    - crates/check_package/**
    - crates/check_plugin_loader/**
    - crates/check_project_layout/**

A-Linter:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_analyze/**
    - crates/check_*_analyze/**

A-Parser:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_parser/**
    - crates/check_*_parser/**
    - crates/check_*_syntax/**

A-Formatter:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_formatter/**
    - crates/check_formatter_test/**
    - crates/check_*_formatter/**

A-Editors:
- changed-files:
  - any-glob-to-any-file:
    - crates/editors/**

A-Diagnostic:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_diagnostics/**
    - crates/check_diagnostics_categories/**
    - crates/check_diagnostics_macros/**

A-Resolver:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_resolver/**

A-Tooling:
- changed-files:
  - any-glob-to-any-file:
    - xtask/**
    - crates/check_ungrammar/**

A-Type-Inference:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_*_type_info/**

A-LSP:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_lsp/**

A-Changelog:
- changed-files:
  - any-glob-to-any-file:
    - CHANGELOG.md

L-Javascript:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_js_*/**

L-Json:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_json_*/**

L-CSS:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_css_*/**

L-HTML:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_html_*/**

L-Grit:
- changed-files:
  - any-glob-to-any-file:
    - crates/check_grit_*/**
