linkWorkspacePackages: true
packages:
  - "packages/aria-data"
  - "packages/tailwindcss-config-analyzer"
  - "crates/check_formatter_test/src/prettier"
  - "benchmark"
  - "packages/@checkjs/*"
ignoredOptionalDependencies:
  - "@checkjs/cli*-"
