[package]
authors.workspace    = true
categories.workspace = true
description          = "Utilities to create Markdown AST for check_markdown_parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_markdown_factory"
repository.workspace = true
version              = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check_markdown_syntax = { workspace = true }
check_rowan           = { workspace = true }

[lints]
workspace = true
