[package]
authors.workspace    = true
categories.workspace = true
description          = "Data structures for tracking type information"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_js_type_info"
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
check_formatter           = { workspace = true }
check_js_syntax           = { workspace = true }
check_js_type_info_macros = { workspace = true }
check_resolver            = { workspace = true }
check_rowan               = { workspace = true }
camino                    = { workspace = true }
hashbrown                 = { workspace = true }
rustc-hash                = { workspace = true }

[dev-dependencies]
check_js_formatter = { workspace = true }
check_js_parser    = { workspace = true }
check_test_utils   = { workspace = true }
insta              = { workspace = true }
