[package]
authors.workspace    = true
categories.workspace = true
description          = "Check's parser shared infrastructure"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_parser"
repository.workspace = true
version              = "0.5.7"

[dependencies]
check_console       = { workspace = true }
check_diagnostics   = { workspace = true }
check_rowan         = { workspace = true }
check_unicode_table = { workspace = true }
drop_bomb           = "0.1.5"
enumflags2          = { workspace = true }
unicode-bom         = { workspace = true }

[lints]
workspace = true
