name: 📝 Formatter bug report
description: Report a bug or regression of the formatter
title: "📝 <TITLE>"
labels: [ "S-Needs triage" ]
type: Bug
body:
  - type: markdown
    attributes:
      value: Thank you for submitting the bug! We'll try to triage it ASAP!
  - type: markdown
    attributes:
      value: |
        Bug reports that don't follow this template will be closed.
        Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: environment
    attributes:
      label: Environment information
      description: Run the command `check rage --formatter` and paste its output here. Please review it, in case there are sensitive information you don't want to share.
      render: bash
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Share the contents of you `check.json` file
      render: JSON
      placeholder: |
        {
          "formatter": {},
          "javascript": {
            "formatter": {}
          }
        }
    validations:
      required: false
  - type: input
    id: playground-link
    attributes:
      label: Playground link
      description: |
        Provide a detailed list of steps that reproduce the issue
        The more information and included steps, the quicker your report can be triaged and addressed!

        You can also use the [playground](https://checkjs.dev/playground/) to share code snippets.
        This is useful to reproduce the issue.

        If you can't use the playground, use `npm create @checkjs/check-reproduction` to quickly create a repository.
      placeholder: https://checkjs.dev/playground/...
    validations:
      required: true
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/checkjs/check/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Check's Code of Conduct
          required: true
