[package]
edition = "2024"
name    = "xtask_codegen"
publish = false
version = "0.0.0"

[dependencies]
anyhow         = { workspace = true }
bpaf           = { workspace = true, features = ["derive"] }
git2           = { version = "0.20.2", default-features = false }
proc-macro2    = { workspace = true, features = ["span-locations"] }
pulldown-cmark = { version = "0.13.0", default-features = false, optional = true }
quote          = "1.0.36"
serde          = { workspace = true, optional = true }
ureq           = "3.0.12"
xtask          = { path = '../', version = "0.0" }

check_analyze         = { workspace = true, features = ["schema"], optional = true }
check_cli             = { workspace = true, optional = true }
check_configuration   = { workspace = true, features = ["schema"], optional = true }
check_css_analyze     = { workspace = true, optional = true }
check_css_syntax      = { workspace = true, optional = true }
check_diagnostics     = { workspace = true, optional = true }
check_graphql_analyze = { workspace = true, optional = true }
check_graphql_parser  = { workspace = true, optional = true }
check_graphql_syntax  = { workspace = true, optional = true }
check_js_analyze      = { workspace = true, optional = true }
check_js_factory      = { workspace = true, optional = true }
check_js_formatter    = { workspace = true, optional = true }
check_js_parser       = { workspace = true, optional = true }
check_js_syntax       = { workspace = true, optional = true }
check_json_analyze    = { workspace = true, optional = true }
check_json_formatter  = { workspace = true, optional = true }
check_json_parser     = { workspace = true, optional = true }
check_json_syntax     = { workspace = true, optional = true }
check_rowan           = { workspace = true, optional = true }
check_service         = { workspace = true, features = ["schema"], optional = true }
check_string_case     = { workspace = true }
check_ungrammar       = { workspace = true }
schemars              = { workspace = true, optional = true }
serde_json            = { workspace = true, optional = true }

[features]
configuration = [
  "check_analyze",
  "check_js_analyze",
  "check_js_syntax",
  "check_json_analyze",
  "check_json_syntax",
  "check_css_analyze",
  "check_css_syntax",
  "check_graphql_analyze",
  "check_graphql_syntax",
  "check_rowan",
  "pulldown-cmark",
  "check_diagnostics",
]
license = ["ureq/default", "ureq/json", "serde", "serde_json"]
schema = [
  "schemars",
  "serde_json",
  "check_analyze",
  "check_rowan",
  "check_service",
  "check_js_syntax",
  "check_js_factory",
  "check_js_formatter",
  "check_json_formatter",
  "check_json_parser",
  "check_diagnostics",
  "check_configuration",
]

[lints]
workspace = true
