[package]
authors.workspace    = true
categories.workspace = true
description          = "Check's semantic model for JavaScript"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_js_semantic"
repository.workspace = true
version              = "0.5.7"

[dependencies]
check_formatter = { workspace = true }
check_js_syntax = { workspace = true }
check_rowan     = { workspace = true }
rust-lapper     = { workspace = true }
rustc-hash      = { workspace = true }
smallvec        = { workspace = true }

[dev-dependencies]
check_console     = { path = "../check_console" }
check_diagnostics = { path = "../check_diagnostics" }
check_js_parser   = { path = "../check_js_parser" }

[lints]
workspace = true
