[package]
authors.workspace    = true
categories.workspace = true
description          = "Check's custom Rowan definition"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_rowan"
repository.workspace = true
version              = "0.5.7"

[dependencies]
check_text_edit = { workspace = true }
check_text_size = { workspace = true }
countme         = { workspace = true, optional = true }
hashbrown       = { workspace = true, features = ["inline-more", "raw-entry"] }
rustc-hash      = { workspace = true }
schemars        = { workspace = true, optional = true }
serde           = { workspace = true, optional = true }

[dev-dependencies]
iai               = "=0.1.1"
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
serde_json        = { workspace = true }

[features]
countme = ["dep:countme"]
schema  = ["dep:schemars", "serde"]
serde   = ["dep:serde", "check_text_size/serde", "check_text_size/serde"]

[[bench]]
harness = false
name    = "mutation"

[lints]
workspace = true
