[package]
authors.workspace    = true
categories.workspace = true
description          = "Functionality for loading plugins and caching them in memory"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_plugin_loader"
repository.workspace = true
version              = "0.0.1"

[dependencies]
check_analyze            = { workspace = true }
check_configuration      = { workspace = true }
check_console            = { workspace = true }
check_css_syntax         = { workspace = true }
check_deserialize        = { workspace = true }
check_deserialize_macros = { workspace = true }
check_diagnostics        = { workspace = true }
check_fs                 = { workspace = true }
check_grit_patterns      = { workspace = true }
check_js_syntax          = { workspace = true }
check_json_parser        = { workspace = true }
check_parser             = { workspace = true }
check_resolver           = { workspace = true }
check_rowan              = { workspace = true }
check_text_size          = { workspace = true }
camino                   = { workspace = true }
grit-pattern-matcher     = { workspace = true }
grit-util                = { workspace = true }
papaya                   = { workspace = true }
rustc-hash               = { workspace = true }
serde                    = { workspace = true }

check_js_runtime = { workspace = true, optional = true }
boa_engine       = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, optional = true, features = ["Win32_System_Threading"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true, optional = true }

[dev-dependencies]
check_js_parser = { workspace = true }
insta           = { workspace = true }

[lints]
workspace = true

[features]
default   = []
js_plugin = ["dep:check_js_runtime", "dep:boa_engine", "dep:libc", "dep:windows"]
