[alias]
check-cli             = "run -p check_cli --release --"
check-cli-dev         = "run -p check_cli --"
codegen               = "run -p xtask_codegen --"
codegen-bindings      = "run -p xtask_codegen --features schema -- bindings"
codegen-configuration = "run -p xtask_codegen --features configuration -- configuration"
# updates a newly created crate
codegen-license = "run -p xtask_codegen --features license -- license"
codegen-migrate = "run -p xtask_codegen --features configuration -- migrate-eslint"
codegen-schema = "run -p xtask_codegen --features schema -- schema"
contributors = "run -p xtask_contributors --"
coverage = "run -p xtask_coverage --profile=release-with-debug --"
documentation = """
    doc \
    -p check_*formatter \
    -p check_control_flow \
    -p check_analyze \
    -p check_*analyze \
    -p check_*_syntax \
    -p check_*_factory \
    -p check_diagnostics \
    -p check_service \
    -p check_cli \
    -p check_console \
    -p check_*parser \
    -p check_text_edit \
    -p check_text_size \
    -p check_js_semantic \
    -p check_markup \
    -p check_rowan
    -p check_string_case \
    -p check_configuration \
    --no-deps
"""
format = "fmt --all --verbose"
lint = "clippy --workspace --all-features --all-targets -- --deny warnings"
new-crate = "run -p xtask_codegen -- new-crate"

[profile.release]
lto = true
