[package]
authors.workspace    = true
categories.workspace = true
description          = "Check's YAML parser"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_yaml_parser"
repository.workspace = true
version              = "0.0.1"

[lints]
workspace = true

[dependencies]
check_console       = { workspace = true }
check_diagnostics   = { workspace = true }
check_parser        = { workspace = true }
check_rowan         = { workspace = true }
check_unicode_table = { workspace = true }
check_yaml_factory  = { workspace = true }
check_yaml_syntax   = { workspace = true }
tracing             = { workspace = true }


[dev-dependencies]
check_test_utils  = { workspace = true }
insta             = { workspace = true }
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
tests_macros      = { workspace = true }
