[package]
authors     = ["Check Developers and Contributors"]
categories  = ["development-tools", "web-programming"]
description = "WebAssembly bindings to the Check workspace API"
edition     = "2024"
homepage    = "https://checkjs.dev/"
keywords    = ["parser", "linter", "formatter", "wasm"]
license     = "MIT OR Apache-2.0"
name        = "check_wasm"
publish     = false
repository  = "https://github.com/checkjs/check"
version     = "1.9.4"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
check_console      = { workspace = true }
check_diagnostics  = { workspace = true }
check_fs           = { workspace = true }
check_service      = { workspace = true }
camino             = { workspace = true }
js-sys             = "0.3.77"
serde              = { workspace = true }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen       = { version = "0.2.100", features = ["serde-serialize"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }


[build-dependencies]
check_js_factory   = { workspace = true }
check_js_formatter = { workspace = true }
check_rowan        = { workspace = true }
check_service      = { workspace = true, features = ["schema"] }
quote              = "1.0.14"
schemars           = { workspace = true }

[lints]
workspace = true

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false
