[package]
description = "Internal script to make sure that the metadata or the rules are correct"
edition     = "2024"
name        = "rules_check"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                = { workspace = true }
check_analyze         = { workspace = true }
check_configuration   = { workspace = true }
check_console         = { workspace = true }
check_css_analyze     = { workspace = true }
check_css_parser      = { workspace = true }
check_css_syntax      = { workspace = true }
check_deserialize     = { workspace = true }
check_diagnostics     = { workspace = true }
check_fs              = { workspace = true }
check_graphql_analyze = { workspace = true }
check_graphql_parser  = { workspace = true }
check_graphql_syntax  = { workspace = true }
check_js_analyze      = { workspace = true }
check_js_parser       = { workspace = true }
check_js_syntax       = { workspace = true }
check_json_analyze    = { workspace = true }
check_json_factory    = { workspace = true }
check_json_parser     = { workspace = true }
check_json_syntax     = { workspace = true }
check_module_graph    = { workspace = true }
check_project_layout  = { workspace = true }
check_rowan           = { workspace = true }
check_service         = { workspace = true }
check_test_utils      = { workspace = true }
camino                = { workspace = true }
pulldown-cmark        = "0.13.0"


[lints]
workspace = true
