[package]
authors.workspace    = true
categories.workspace = true
description          = "ECMAScript runtime for JS plugins"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_js_runtime"
repository.workspace = true
version              = "0.0.1"

[dependencies]
check_analyze     = { workspace = true }
check_diagnostics = { workspace = true }
check_resolver    = { workspace = true }
check_text_size   = { workspace = true }
boa_engine        = { workspace = true }
camino            = { workspace = true }
rustc-hash        = { workspace = true }

[lints]
workspace = true
