[package]
authors.workspace    = true
categories.workspace = true
description          = "Check's core functionality"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "check_service"
publish              = false
repository.workspace = true
version              = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
append-only-vec         = "0.1.7"
check_analyze           = { workspace = true, features = ["serde"] }
check_configuration     = { workspace = true }
check_console           = { workspace = true }
check_css_analyze       = { workspace = true }
check_css_formatter     = { workspace = true }
check_css_parser        = { workspace = true }
check_css_semantic      = { workspace = true }
check_css_syntax        = { workspace = true }
check_deserialize       = { workspace = true }
check_diagnostics       = { workspace = true, features = ["camino"] }
check_formatter         = { workspace = true, features = ["serde"] }
check_fs                = { workspace = true, features = ["serde"] }
check_glob              = { workspace = true }
check_graphql_analyze   = { workspace = true }
check_graphql_formatter = { workspace = true }
check_graphql_parser    = { workspace = true }
check_graphql_syntax    = { workspace = true }
check_grit_formatter    = { workspace = true }
check_grit_parser       = { workspace = true }
check_grit_patterns     = { workspace = true, features = ["serde"] }
check_grit_syntax       = { workspace = true }
check_html_formatter    = { workspace = true, features = ["serde"] }
check_html_parser       = { workspace = true }
check_html_syntax       = { workspace = true }
check_js_analyze        = { workspace = true }
check_js_factory        = { workspace = true, optional = true }
check_js_formatter      = { workspace = true, features = ["serde"] }
check_js_parser         = { workspace = true }
check_js_semantic       = { workspace = true }
check_js_syntax         = { workspace = true }
check_js_type_info      = { workspace = true }
check_json_analyze      = { workspace = true }
check_json_formatter    = { workspace = true, features = ["serde"] }
check_json_parser       = { workspace = true }
check_json_syntax       = { workspace = true }
check_module_graph      = { workspace = true, features = ["serde"] }
check_package           = { workspace = true }
check_parser            = { workspace = true }
check_plugin_loader     = { workspace = true }
check_project_layout    = { workspace = true }
check_resolver          = { workspace = true }
check_rowan             = { workspace = true, features = ["serde"] }
check_string_case       = { workspace = true }
check_text_edit         = { workspace = true }
camino                  = { workspace = true }
crossbeam               = { workspace = true }
enumflags2              = { workspace = true, features = ["serde"] }
getrandom               = { workspace = true, features = ["js"] }
ignore                  = { workspace = true }
notify                  = { version = "8.1.0", features = ["crossbeam-channel"] }
papaya                  = { workspace = true }
rayon                   = { workspace = true }
regex                   = { workspace = true }
rustc-hash              = { workspace = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true, features = ["derive"] }
serde_json              = { workspace = true, features = ["raw_value"] }
smallvec                = { workspace = true, features = ["serde"] }
tokio                   = { workspace = true, features = ["sync"] }
tracing                 = { workspace = true, features = ["attributes", "log"] }
web-time                = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[features]
js_plugin = ["check_plugin_loader/js_plugin"]
schema = [
  "dep:schemars",
  "check_configuration/schema",
  "check_js_analyze/schema",
  "check_formatter/schema",
  "check_js_factory",
  "check_js_syntax/schema",
  "check_text_edit/schema",
  "check_json_syntax/schema",
  "check_css_syntax/schema",
  "check_graphql_syntax/schema",
  "check_grit_syntax/schema",
  "check_grit_patterns/schema",
  "check_html_syntax/schema",
  "check_html_formatter/schema",
  "check_fs/schema",
  "check_module_graph/schema",
]

[lints]
workspace = true
